#!/bin/sh
# This script is only used for developement. It is removed by the 
# distribution process. 

set -e

REGDIR=regs

REGFILES=${REGFILES:="gl.xml"}

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -tag debug -tag annot -classic-display \
                          -use-ocamlfind"}

map()
{
    local f=$1
    shift
    for n in $*; do
        $f $n
    done
}

add_dir()
{
    echo -n "$REGDIR/$1 "
}

REGS=$(map add_dir $REGFILES)

action () 
{
    case $1 in
      default)      $OCAMLBUILD $* ;;
      apiquery)     $OCAMLBUILD apiquery.native ;;
      support)      action apiquery
                    check_regs
                    ./apiquery.native $REGS -mli -api gl3.3 > src/tgl3.mli
                    ./apiquery.native $REGS -ml -api gl3.3 > src/tgl3.ml
                    ./apiquery.native $REGS -mli -api gl4.5 > src/tgl4.mli
                    ./apiquery.native $REGS -ml -api gl4.5 > src/tgl4.ml
                    ./apiquery.native $REGS -mli -api gles2.0 > src/tgles2.mli
                    ./apiquery.native $REGS -ml -api gles2.0 > src/tgles2.ml
                    ./apiquery.native $REGS -mli -api gles3.1 > src/tgles3.mli
                    ./apiquery.native $REGS -ml -api gles3.1 > src/tgles3.ml
                    ;;
      tgls)         $OCAMLBUILD \
                    tgl3.cmxa dlltgl3.so \
                    tgl4.cmxa dlltgl4.so \
                    tgles2.cmxa dlltgles2.so \
                    tgles3.cmxa dlltgles3.so 
                    ;;
      doc)          shift; pkg-doc $* doc/api-dev.docdir ;;
      clean)        $OCAMLBUILD -clean
                    rm -f src/tgl3.mli src/tgl3.ml src/tgl4.mli src/tgl4.ml \
                          src/tgles2.mli src/tgles2.ml src/tgles3.mli \
                          src/tgles3.ml
                    ;;
      *)            $OCAMLBUILD $* ;;
    esac
} 

check_regs ()
{
    for file in $REGFILES; do
        if [ ! -f "$REGDIR/$file" ]; then 
            echo "Missing file $REGDIR/$file, see DEVEL.md"
            exit 1
        fi
    done
}

if [ $# -eq 0 ]; 
then action default ; 
else action $*; fi
